### ISSUE TITLE
`Barber::PrecompilerError` after setting up project

### ISSUE THREAD

**Issue by joonty** [vicramon/ember-data-rails-example#2]
I tried setting up the project in the usual fashion (`bundle`, `rake db:migrate`, etc.), but after starting the server all requests give this error:

> Showing /home/jon/projects/ember-data-rails-example/app/views/layouts/application.html.erb where line #6 raised:
> 
> Pre compilation failed for: | Hi, I'm a global modal.
> br
> br
> a href="#" click="close" close
> 
> . Compiler said: TypeError: Cannot read property '3' of undefined
>   (in /home/jon/projects/ember-data-rails-example/app/assets/javascripts/templates/center_modal.js.emblem)

The interesting part of the stack trace shows:

> barber (0.4.2) lib/barber/precompiler.rb:15:in `rescue in compile'
> barber (0.4.2) lib/barber/precompiler.rb:13:in`compile'
> barber (0.4.2) lib/barber/precompiler.rb:8:in `compile'
> barber-emblem (0.1.1) lib/barber/emblem/ember_precompilers.rb:10:in`compile'
> barber-emblem (0.1.1) lib/barber/emblem/ember_precompilers.rb:6:in `call'
> emblem-rails (0.1.1) lib/emblem/rails/template.rb:52:in`precompile_ember_emblem'
> emblem-rails (0.1.1) lib/emblem/rails/template.rb:20:in `evaluate'

So it looks like the emblem files are failing to parse. Any ideas on this? Thanks.

**Comment by simo163** [comment]
In one of our projects was working great, suddenly got the same error, any suggestions will be very appreciated, there are really few options for this. I think this caused because we changed some gems versions but really not sure, and even we returned to previous commits, didn't solve it! 
```
  Barber::PrecompilerError at /
  Pre compilation failed for: .row
 .
```

**Comment by frankapimenta** [comment]
@simo163 does it happen to you that the ember app is loaded fine but all the emblem templates are not loaded?

**Comment by simo163** [comment]
@frankapimenta yes exactly, including it happened to all my ember projects that use emblem. Any idea?
